### ISSUE TITLE
Get python error AttributeError: 'SysLogHandler' object has no attribute 'socket'

### ISSUE THREAD

**Issue by kingfisher77** [Glideh/docker-cron-rotate-backups#1]
When i use this image it is silently not working. If i execute
`/usr/local/bin/rotate-backups "--hourly=24 --daily=7 --weekly=1 --monthly=1 --yearly=1" /data`
directly in the container, the error occurs:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 2034, in shutdown
    h.close()
  File "/usr/local/lib/python3.7/logging/handlers.py", line 892, in close
    self.socket.close()
AttributeError: 'SysLogHandler' object has no attribute 'socket'
```

**Comment by kingfisher77** [comment]
Did you solve this? The same happens to me.

**Comment by kingfisher77** [comment]
The error was the double quotes.
